name: perfusion
channels:
  - pytorch
  - xformers
  - defaults
dependencies:
  - python
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - xformers
  - pip:
      - albumentations==1.3.1
      - pytorch-lightning==1.6.0
      - omegaconf==2.1.1
      - einops==0.6.1
      - transformers==4.31.0
      - kornia==0.7.0
      - open_clip_torch==2.20.0
      - git+https://github.com/openai/CLIP.git
      - pillow==9.5.0
      - diffusers
      - transformers
